# Note: Template variables must use double braces format without spaces
# Do not auto-format this file as it will break template variable syntax
externalId: loc_fltr_{{location}}
name: InField - {{location_name}}
description: Infield {{location_description}}
dataModels:
  - space: customer_idm_extention
    externalId: ExtensionDataModel
    version: v1 # should be latest version of the data model
instanceSpaces:
  - sp_infield_{{location}}_assets
  - sp_infield_{{location}}_maintenance
  - sp_infield_{{location}}_timeseries
  - sp_infield_{{location}}_files_1
  - sp_infield_{{location}}_files_2
  - sp_infield_{{location}}_app_inst
views:
  - externalId: ExtendedMaintenanceOrder
    space: customer_idm_extention
    version: v1
    representsEntity: MAINTENANCE_ORDER
  - externalId: ExtendedOperation
    space: customer_idm_extention
    version: v1
    representsEntity: OPERATION
  - externalId: ExtendedNotification
    space: customer_idm_extention
    version: v1
    representsEntity: NOTIFICATION
  - externalId: ExtendedAsset
    space: customer_idm_extention
    version: v1
    representsEntity: ASSET
