name: Upload to GCP Bucket

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  upload-to-gcp:
    runs-on: ubuntu-latest
    environment: CD

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install required libraries
        run: |
           name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          APPS_CDN_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.APPS_CDN_SERVICE_ACCOUNT_CREDENTIALS }}
        run: |
          python sync_to_cdn.py