name: Upload to GCP Bucket
on:
  push:
    branches:
      - main # Trigger on push to the main branch
  workflow_dispatch: # Allows manual triggering
jobs:
  upload-to-gcp:
    runs-on: ubuntu-latest
    environment: CD
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up GCP authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.APPS_CDN_SERVICE_ACCOUNT_CREDENTIALS }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: 'cognitedata-production'
      - name: Upload to GCP CDN Bucket
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: 'data'  # Updated source path
          destination: 'apps-cdn-bucket-cognitedata-production/toolkit' # The destination for the file/folder in the form bucket-name or with an optional prefix in the form bucket-name/prefix
          concurrency: '10' # Optional: Number of concurrent uploads
          parent: false # Whether the parent directory should be included in GCS destination path.
          headers: |-
            cache-control: 'public, max-age=31536000'
          process_gcloudignore: false
