name: Upload to GCP Bucket
on:
  push:
    branches:
      - main # Trigger on push to the main branch
  workflow_dispatch: # Allows manual triggering
jobs:
  upload-to-gcp:
    runs-on: ubuntu-latest
    environment: CD
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up GCP authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.APPS_CDN_SERVICE_ACCOUNT_CREDENTIALS }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: 'cognitedata-production'
      - name: Upload files if not present in GCS
        run: |
          BUCKET_NAME="apps-cdn-bucket-cognitedata-production"
          DEST_PREFIX="toolkit"
          SOURCE_DIR="data"

          # Navigate to the source directory
          cd "$SOURCE_DIR"

          # Find and process all files in the source directory
          for FILE in $(find . -type f); do
            # Remove leading './' from the file path
            RELATIVE_PATH=${FILE#./}
            DEST_PATH="gs://${BUCKET_NAME}/${DEST_PREFIX}/${RELATIVE_PATH}"
            
            curl -X POST \
              -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @"$FILE" \
              "https://storage.googleapis.com/upload/storage/v1/b/<BUCKET_NAME>/o?uploadType=media&name=<DESTINATION_PATH>"
          done
