name: Upload to GCP Bucket

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  upload-to-gcp:
    runs-on: ubuntu-latest
    environment: CD

    steps:
      - name: Checkout code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Set up Python and install dependencies
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: "3.9"

      - name: Install required libraries
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          APPS_CDN_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.APPS_CDN_SERVICE_ACCOUNT_CREDENTIALS }}
        run: |
          python sync_to_cdn.py